CREATE TABLE Usuario
(
	IdUsuario UNIQUEIDENTIFIER NOT NULL,
	Nome NVARCHAR(150) NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Senha NVARCHAR(40) NOT NULL,
	DataCriacao DATETIME NOT NULL,
	PRIMARY KEY (IdUsuario)

)

CREATE TABLE Contato
(
	IdContato UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Nome NVARCHAR(150) NOT NULL,
	Telefone NVARCHAR(20) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	DataNascimento DATE NOT NULL,
	Tipo INT NOT NULL,
	IdUsuario UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (IdUSuario) REFERENCES Usuario(IdUsuario)
	
)