CREATE TABLE Usuario
(
	IdUsuario UNIQUEIDENTIFIER NOT NULL,
	Nome NVARCHAR(150) NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Senha NVARCHAR(40) NOT NULL,
	DataCriacao DATETIME NOT NULL,
	PRIMARY KEY (IdUsuario)

)